name: Debian

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant virtualbox
      - run: |
          vagrant up
          vagrant plugin install vagrant-vbguest
          vagrant package --vagrantfile ./Vagrantfile
      - name: List generated box file (debug)
        run: |
          find . -name "package.box"
          # gzip -c package.box > package.box.gz
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: ${{ github.workspace }}/*.box.gz
      #     # 将保留天数设置为3天，最多可设置90天
      #     retention-days: 3
      - run: |
          vagrant box add --name debian-test --provider=virtualbox ./package.box
      - name: test
        run: |
          vagrant destroy -f
          mkdir -p ./tmp
          cd ./tmp
          cp package.box ./tmp/package.box
          vagrant init debian-test
          vagrant up
          vagrant ssh --command "neovim --version"
          vagrant halt
