name: Debian

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        type: boolean
        required: true
        default: false
  push:
    branches: [main]
    paths:
      - '.github/workflows/debian.yml'
      - 'debian/Vagrantfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # 赋予写入的权限，否则无法发布release
      contents: write
    steps:
      - uses: actions/checkout@main
      - name: Setup installation
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant virtualbox
      - name: Build box file by Vagrantfile
        run: |
          cd debian
          vagrant up
          vagrant plugin install vagrant-vbguest
          vagrant package --vagrantfile ./debian/Vagrantfile
      - name: List generated box file (debug)
        if: inputs.release
        run: |
          find . -name "package.box"
          gzip -c package.box > package.box.gz
          # 上海时区
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          save_date=$(TZ="Asia/Shanghai" date +'%Y%m%d')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "TAG=$save_date" >> $GITHUB_ENV
      - name: Release
        if: inputs.release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG }}
          body: |
            ### Box files
          artifacts: "${{ github.workspace }}/package.box.gz"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
